name: Code Coverage

on: [push, pull_request]

env:
  RUST_BACKTRACE: 1

jobs:  
  generate_coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    
    - name: Install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: nightly
          override: true
          components: llvm-tools-preview
    
    - name: Build cfitsio
      run: |
          # Install dependencies
          curl "https://heasarc.gsfc.nasa.gov/FTP/software/fitsio/c/cfitsio-3.49.tar.gz" -o cfitsio.tar.gz
          tar -xf cfitsio.tar.gz
          rm cfitsio.tar.gz
          cd cfitsio-3.49
          # Enabling SSE2/SSSE3 could cause portability problems, but it's unlikely that anyone
          # is using such a CPU...
          # https://stackoverflow.com/questions/52858556/most-recent-processor-without-support-of-ssse3-instructions
          # Disabling curl just means you cannot fits_open() using a URL.
          CFLAGS="-O3" ./configure --prefix=/usr/local --enable-reentrant --enable-sse2 --enable-ssse3 --disable-curl
          make -j
          sudo make install
          sudo ldconfig
          cd ..

    - name: Install OS and Cargo Packages
      run: |         
        sudo apt-get update 
        && sudo apt-get install -y lcov clang curl zip unzip libssl-dev jq 
        && cargo update
        && cargo install --force cargo-make cargo-binutils grcov
      env:
        DEBIAN_FRONTEND: noninteractive
        
    - name: Generate test lcov coverage into coverage/ dir
      env:
        LD_LIBRARY_PATH: /usr/local/lib/
        CARGO_INCREMENTAL: 0
        RUSTFLAGS: "-Zprofile -Ccodegen-units=1 -Copt-level=0 -Coverflow-checks=off"
        RUSTDOCFLAGS: "-Cpanic=abort"
        LLVM_PROFILE_FILE: json5format-%m.profraw
      run: |
        mkdir -p coverage
        cargo build
        cargo test
        zip -0 ccov.zip `find . \( -name "mwalib*.gc*" \) -print`
        grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" -o coverage/coverage.lcov

    - name: Upload reports to codecov.io
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
