name: Code Coverage

on: [push, pull_request]

env:
  RUST_BACKTRACE: 1  
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  generate_coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y \
          tzdata \
          build-essential \
          pkg-config \
          git \
          lcov \
          libcfitsio-dev \
          ;
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: llvm-tools

    - name: Generate test lcov coverage into coverage/ dir
      run: |
        mkdir -p coverage
        cargo llvm-cov clean --workspace
        maturin develop --features=python,cfitsio-static
        pytest tests --cov=mwalib --cov-report xml:coverage/coverage.xml tests
        cargo llvm-cov --features cfitsio-static,examples --lcov --output-path coverage/coverage.lcov
        # this uses the result of the previous run to generate a text summary
        cargo llvm-cov report

    - name: Upload reports to codecov.io. Codecov should automatically merge the python and rust coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}