name: Code Coverage

on: [push, pull_request]

env:
  RUST_BACKTRACE: 1

jobs:
  generate_coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo apt install -y \
          tzdata \
          build-essential \
          pkg-config \
          git \
          lcov \
          libcfitsio-dev \
          ;
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: llvm-tools-preview

    - name: install cargo-llvm-cov
      run: cargo install cargo-llvm-cov

    - name: Generate test lcov coverage into coverage/ dir
      run: |
        mkdir -p coverage
        cargo llvm-cov --lib --lcov --output-path coverage/coverage.lcov
        # this uses the result of the previous run to generate a text summary
        cargo llvm-cov --no-run

    - name: Upload reports to codecov.io
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
