name: Code Coverage

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  generate_coverage:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Checkout sources
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            tzdata \
            build-essential \
            pkg-config \
            git \
            lcov \
            gpg \
            ;
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Install stable minimal toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: llvm-tools

      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov

      - name: Install uv and Python
        uses: astral-sh/setup-uv
        with:
          python-version: "3.14"

      - name: Generate test lcov coverage into coverage/ dir
        env:
          MATURIN_PEP517_ARGS: --features=cfitsio-static,examples,python,pyo3/extension-module
        run: |
          mkdir -p coverage
          cargo llvm-cov clean --workspace

          # Run rust tests to generate test data
          cargo test --features=cfitsio-static,examples,python

          # Build python module and install dev dependencies
          uv sync --locked

          # Coverage for python tests
          uv run --no-sync --with pytest-cov pytest tests --cov=mwalib --cov-report xml:coverage/coverage.xml

          # Coverage for rust tests
          cargo llvm-cov --features=cfitsio-static,examples,python --lcov --output-path coverage/coverage.lcov

          # this uses the result of the previous run to generate a text summary
          cargo llvm-cov report

      - name: Upload reports to codecov.io. Codecov should automatically merge the python and rust coverage
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
