name: Python tests

on: [push, pull_request]

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: macos-latest
            python-version: [3.7, 3.8, 3.9, 3.10]
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: stable
          override: true
    
    - name: Run pytests
      run: |
          pip3 install maturin==1.2.3
          if [[ "$OSTYPE" == "darwin"* ]]; then
            brew install automake
          fi

          maturin develop --features=python,cfitsio-static --strip

          pip install pytest          
          pytest
