name: MacOS Tests

on: [push, pull_request]

env:
  RUST_BACKTRACE: 1  

jobs:
  test_macos:
    strategy:
      matrix:
        os: ["macOS-latest"]
    runs-on: ${{ matrix.os }}    

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    
    - name: Uninstall curl and install cfitsio
      run: |
          brew uninstall --ignore-dependencies curl
          brew install cfitsio

    - name: Run tests
      run: MWALIB_LINK_STATIC_CFITSIO=1 cargo test --release --verbose
