name: MacOS Tests

on: [push, pull_request]

env:
  RUST_BACKTRACE: 1
  LIBCURL_CFLAGS: "-I/usr/local/opt/curl/include" 
  LIBCURL_LIBS: "-L/usr/local/opt/curl/lib -lcurl"

jobs:
  test_macos:
    strategy:
      matrix:
        os: ["macOS-latest"]
    runs-on: ${{ matrix.os }}    

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
    
    - name: Install curl and cfitsio
      run: |
          brew update
          brew upgrade curl          
          brew install cfitsio

    - name: Run tests
      run: MWALIB_LINK_STATIC_CFITSIO=1 cargo test --release --verbose
